# Usa una imagen base de Node
FROM node:22

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de configuración del proyecto
COPY package.json package-lock.json ./

# Instala todas las dependencias
RUN npm install

# Copia el resto del código fuente del proyecto
COPY . .

# Expone el puerto 5173
EXPOSE 5173

WORKDIR /app/frontend

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]